"use client";
import { FormEvent, useMemo, useState } from "react";
type Application={id:number;company:string;role:string;city:string;stage:string;date:string;next:string;resume:string;tone:string};
const resumes=["产品经理版 v3","商业分析版 v2","增长运营版 v4","通用版 v5"];
const initial:Application[]=[
{id:1,company:"字节跳动",role:"产品经理",city:"北京",stage:"一面",date:"08/08",next:"今天 19:00",resume:resumes[0],tone:"purple"},
{id:2,company:"腾讯",role:"商业分析",city:"深圳",stage:"笔试",date:"08/10",next:"明天 20:00 截止",resume:resumes[1],tone:"blue"},
{id:3,company:"小红书",role:"用户增长",city:"上海",stage:"已投递",date:"08/12",next:"已等待 3 天",resume:resumes[2],tone:"red"},
{id:4,company:"美团",role:"策略运营",city:"北京",stage:"网申",date:"08/13",next:"补充作品集",resume:resumes[3],tone:"yellow"}];
const stages=["全部","网申","已投递","笔试","一面","二面","Offer"];
export default function Home(){
const[active,setActive]=useState("总览"),[filter,setFilter]=useState("全部"),[apps,setApps]=useState(initial),[showAdd,setShowAdd]=useState(false),[toast,setToast]=useState("");
const visible=useMemo(()=>filter==="全部"?apps:apps.filter(a=>a.stage===filter),[apps,filter]);
const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(""),2200)};
const add=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);setApps(p=>[{id:Date.now(),company:String(d.get("company")),role:String(d.get("role")),city:String(d.get("city")),stage:"网申",date:"08/13",next:"完善申请信息",resume:String(d.get("resume")),tone:"green"},...p]);setShowAdd(false);notify("已加入投递清单，并关联简历版本")};
const go=(x:string)=>{setActive(x);document.getElementById(x)?.scrollIntoView({behavior:"smooth"})};
return <main>
<header className="topbar"><button className="brand" onClick={()=>go("总览")}><span className="brandmark">候</span><span>候鸟</span></button><nav aria-label="主导航">{["总览","投递","表格助手","面试复盘"].map(x=><button key={x} className={active===x?"active":""} onClick={()=>go(x)}>{x}</button>)}</nav><div className="header-actions"><button className="round" aria-label="搜索">⌕</button><button className="round" aria-label="通知">♧<i/></button><button className="avatar">YW</button></div></header>
<section className="hero" id="总览"><div className="eyebrow">2027 届 · 秋招进行中</div><h1>早上好，<em>今天有 2 件事</em><br/>值得你优先处理。</h1><p>把精力留给真正重要的机会，其余的交给候鸟。</p><div className="hero-date"><b>13</b><span>AUG<br/>周四</span></div></section>
<section className="priority"><div className="section-title"><span>今日优先</span><small>2 项待办</small></div><div className="task-grid"><article className="task urgent"><div className="task-time">19:00</div><div><span className="tag">面试</span><h3>字节跳动 · 产品经理一面</h3><p>提前 30 分钟检查设备与网络</p></div><button onClick={()=>notify("已标记准备完成")}>准备面试 <span>→</span></button></article><article className="task"><div className="task-time">20:00</div><div><span className="tag blue">截止</span><h3>腾讯 · 在线笔试</h3><p>剩余 9 小时 · 预计用时 90 分钟</p></div><button onClick={()=>notify("已打开笔试准备清单")}>查看详情 <span>→</span></button></article></div></section>
<section className="content-grid" id="投递"><div className="pipeline"><div className="block-head"><div><small>APPLICATIONS</small><h2>我的投递</h2></div><button className="primary" onClick={()=>setShowAdd(true)}>＋ 添加投递</button></div><div className="stage-tabs">{stages.map(s=><button className={filter===s?"selected":""} onClick={()=>setFilter(s)} key={s}>{s}{s==="全部"&&<b>{apps.length}</b>}</button>)}</div><div className="app-list">{visible.map(a=><article className="app-row" key={a.id}><span className={`company-logo ${a.tone}`}>{a.company[0]}</span><div className="company"><h3>{a.company}</h3><p>{a.role} · {a.city}</p><span className="resume-pill">▧ {a.resume}</span></div><span className="applied">投递于 {a.date}</span><span className={`stage ${a.tone}`}>{a.stage}</span><div className="next"><b>{a.next}</b><small>下一步</small></div><button className="more" aria-label={`${a.company}更多操作`}>•••</button></article>)}</div><button className="view-all" onClick={()=>setFilter("全部")}>查看全部投递 <span>→</span></button></div>
<aside><article className="side-card" id="表格助手"><div className="card-icon mint">▤</div><div><small>表格助手</small><h3>个人信息库</h3></div><span className="progress">82%</span><div className="progressbar"><i/></div><p>再补充 3 项，就能更快填写网申表格</p><button onClick={()=>notify("个人信息库已打开")}>继续完善 <span>→</span></button></article><article className="side-card"><div className="card-icon sky">▧</div><div><small>简历库</small><h3>4 个简历版本</h3></div><span className="count">12<small>次投递</small></span><p>每条投递都会保留当时使用的简历版本</p><div className="chips"><span>产品经理 v3</span><span>通用 v5</span></div><button onClick={()=>notify("简历库已打开")}>管理简历 <span>→</span></button></article><article className="side-card interview" id="面试复盘"><div className="card-icon peach">✦</div><div><small>面试复盘</small><h3>上次：阿里巴巴</h3></div><span className="count">12<small>道题</small></span><p>最近记录于 8 月 11 日</p><div className="chips"><span>产品思维</span><span>业务分析</span><span>行为面试</span></div><button onClick={()=>notify("已新建一份面试复盘")}>记录新复盘 <span>＋</span></button></article><article className="quote"><span>“</span><p>不必追逐每一次风，<br/>选对方向，然后坚定地飞。</p><small>— 今日寄语</small></article></aside></section>
<footer><span>候鸟 · 陪你走过每一程</span><div><b>28</b> 已投递　<b>6</b> 面试中　<b>1</b> Offer</div></footer>
{showAdd&&<div className="modal" role="dialog" aria-modal="true" aria-label="添加投递"><form onSubmit={add}><button type="button" className="close" onClick={()=>setShowAdd(false)}>×</button><small>NEW APPLICATION</small><h2>添加一条投递</h2><label>公司名称<input name="company" required placeholder="例如：网易"/></label><label>申请岗位<input name="role" required placeholder="例如：产品经理"/></label><label>工作城市<input name="city" required placeholder="例如：杭州"/></label><label>使用的简历<select name="resume" required defaultValue=""><option value="" disabled>选择本次使用的简历版本</option>{resumes.map(r=><option key={r}>{r}</option>)}</select></label><button className="submit">保存到投递清单</button></form></div>}{toast&&<div className="toast">✓ {toast}</div>}
</main>}
